---
- hosts: all
  sudo: yes
  gather_facts: yes
  roles:
    - geerlingguy.packer-rhel
    - geerlingguy.nfs
  tasks:
    # - name: update all packages
    #   yum: name=* state=latest

    # - name: install nfs tools
    #   yum: name={{item}} state=latest
    #   with_items:
    #     - firewalld
    #     - bind-utils
    #     - lsscsi
    #     - sysfsutils
    #     - net-tools
    #     - nfs-utils
    #     - libnfsidmap
    #     - libselinux-python

    # - name: start NFS services
    #   service:
    #     name: "{{item}}"
    #     state: restarted
    #     enabled: yes
    #   with_items:
    #     - rpcbind
    #     - nfs-server
    #     - rpc-statd
    #     - nfs-idmapd
    #     - firewalld
    
    - name: install zsh requirements
      yum: name={{item}} state=latest
      with_items:
        - curl
        - wget
        - git
        - zsh

    - user: name=redman comment="Ross Edman" shell=/bin/zsh 
    - user: name=redman groups=wheel append=yes
    - user: name=vagrant shell=/bin/zsh

    - git: repo=git://github.com/robbyrussell/oh-my-zsh.git dest=/home/vagrant/.oh-my-zsh accept_hostkey=True
    - git: repo=git://github.com/robbyrussell/oh-my-zsh.git dest=/home/redman/.oh-my-zsh accept_hostkey=True

    - command: cp /home/redman/.oh-my-zsh/templates/zshrc.zsh-template /home/redman/.zshrc creates=/home/redman/.zshrc
    - command: cp /home/vagrant/.oh-my-zsh/templates/zshrc.zsh-template /home/vagrant/.zshrc creates=/home/vagrant/.zshrc

    - name: setup ~/.ssh directory
      file:
        dest: /home/redman/.ssh/
        state: directory

    - name: authorize ssh key for login
      authorized_key:
        user: redman
        key: "{{ lookup('file', '/tmp/provision/files/id_rsa.pub') }}"

    - name: change visudo file for passwordless logins
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: ^%wheel ALL\=
        line: "%wheel ALL=(ALL) NOPASSWD:ALL"
        validate: visudo -cf %s

    - name: install dynmotd
      command: cp /tmp/provision/files/dynmotd /usr/local/bin/dynmotd creates=/usr/local/bin/dynmotd

    - command: chmod 755 /usr/local/bin/dynmotd

    - lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        regexp: ^PrintMotd
        line: PrintMotd no

    - lineinfile:
        dest: /etc/profile
        state: present
        regexp: ^/usr/local/bin/dynmotd
        line: /usr/local/bin/dynmotd
