---
- hosts: all
  sudo: yes
  gather_facts: yes
  roles:
    - geerlingguy.packer-debian
    - geerlingguy.nfs
  tasks:
    - name: install zsh requirements
      apt: name={{item}} state=latest
      with_items:
        - curl
        - wget
        - git
        - zsh

    - name: clone oh-my-zsh
      git: 
        repo: git://github.com/robbyrussell/oh-my-zsh.git 
        dest: "/home/{{item}}/.oh-my-zsh" 
        accept_hostkey: True
      with_items:
        - vagrant
        - redman

    - name: install .zshrc file
      command: "cp /home/{{item}}/.oh-my-zsh/templates/zshrc.zsh-template /home/{{item}}/.zshrc creates=/home/{{item}}/.zshrc"
      with_items:
        - vagrant
        - redman

    - user: name=redman comment="Ross Edman" shell=/bin/zsh 
    - user: name=redman groups=sudo append=yes
    - user: name=vagrant shell=/bin/zsh

    - name: setup ~/.ssh directory
      file:
        dest: /home/redman/.ssh/
        state: directory

    - name: authorize ssh key for login
      authorized_key:
        user: redman
        key: "{{ lookup('file', '/tmp/provision/files/id_rsa.pub') }}"

    - name: change visudo file for passwordless logins
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: ^%sudo ALL\=
        line: "%sudo ALL=(ALL) NOPASSWD:ALL"
        validate: visudo -cf %s